package com.rest.example.controller;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.rest.example.bean.Stock;
import com.rest.example.persistence.StockRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class StockController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private StockRepository stockRepository;

	@GetMapping(path = "/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser(
	        @RequestParam String symbol,
	        @RequestParam Date date,
	        @RequestParam Double previousClose,
	        @RequestParam Double price) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Stock n = new Stock();
		n.setSymbol(symbol);
		n.setDate(date);
		n.setPreviousClose(previousClose);
		n.setPrice(price);
		stockRepository.save(n);
		return "Saved new entry";
	}

	@GetMapping(path = "/delete") // Map ONLY GET Requests
	public @ResponseBody String deleteUser(
	        @RequestParam String symbol) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Stock n = new Stock();
		n.setSymbol(symbol);
		stockRepository.delete(n);
		return "Deleted an entry";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Stock> getAllUsers() {
		// This returns a JSON or XML with the users
		return stockRepository.findAll();
	}
}
